Send data to gsheet
DadosAbertosDeFeira/vacinometro pull request #6
Opened 2021-01-26 21:49 UTC by felipelfb

2021-01-26 21:51 UTC, felipelfb commented
@anapaulagomes Criei o PR para ter o review. Depois tento criar o Github Action :smiley:

2021-01-27 07:29 UTC, anapaulagomes requested changes
Ficou ótimo! 🎖️ Mas o ideal é colocarmos esse código em um pipeline - dessa forma será processado corretamente pelo Scrapy em casos de retries.

2021-01-27 07:30 UTC, anapaulagomes commented
Aqui um exemplo: https://github.com/DadosAbertosDeFeira/covid19-bahia/pull/4

2021-01-28 15:37 UTC, felipelfb commented
@anapaulagomes atualizado :+1:

2021-01-29 14:15 UTC, anapaulagomes approved these changes
Boa! 👏🏽

2021-01-29 14:16 UTC, merged